# Gemfile for SICK Analytics Platform
source "https://rubygems.org"

gem 'selenium-cucumber', '~> 3.1', '>= 3.1.5'
gem 'colorize', '~> 0.7.7'
gem 'couchrest', '~> 2.0'
gem 'cucumber-rest-bdd', '~> 0.4.4'
gem 'websocket-client-simple', '~> 0.3.0'
gem 'cassandra-driver', '~> 3.1'
gem 'unitwise', '~> 2.0'
gem 'rspec', '3.4.0'
gem 'rspec-expectations', '3.4.0'

ruby '2.2.6'